services:
    front:
        container_name: olivet-front
        build:
          context: ./frontend
          dockerfile: Dockerfile.dev
        env_file: 
          - ./frontend/.env
        volumes:
          - ./frontend/src/:/app/src
          - /app/node_modules
        ports:
          - 3000:3000
    back:
        container_name: olivet-back
        build: ./backend
        env_file: 
            - ./backend/.env.docker
        ports:
            - 4000:4000
        command: npm run dev
        volumes:
            - ./backend/src/:/app/src/
    mongodb:
      image: mongo
      volumes:
        - ./data:/data/db