version: "3"

services:
  server:
    build: ./backend
    command: sh -c "yarn run build && yarn run prod"
    expose:
      - 5000
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - SERVER_PORT=5000
      - DB_URL=mongodb://mongodb:27017/usmolivet
  client:
    build: ./frontend
    command: sh -c "yarn run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/graphql
  mongodb:
    image: mongo:4.4.9
    volumes:
      - ./data/db:/data/db
      - ./data/backup:/data/backup
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
volumes:
  web-client-build:
