version: "3"

services:
  server:
    container_name: olivet-back
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - SERVER_PORT=4000
      - DB_URL=mongodb://mongodb:27017/usmolivet
    ports:
      - 4000:4000
    command: yarn run dev
    volumes:
      - ./backend/src/:/app/src
  client:
    container_name: olivet-front
    build: ./frontend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:4000/graphql
    volumes:
      - ./frontend/src/:/app/src
    ports:
      - 3000:3000
  mongodb:
    image: mongo:4.4.9
    volumes:
      - ./data:/data/db
