services:
    front:
        container_name: olivet-front
        build: ./frontend
        ports:
            - 3000:80
        volumes:
            - ./frontend/src/:/app/src
            - /app/node_modules
    back:
        container_name: olivet-back
        build: ./backend
        env_file: 
            - ./backend/.env.production
        ports:
            - 4000:4000
        volumes:
            - ./backend/src/:/app/src/
    mongodb:
        image: mongo
        volumes:
            - ./data:/data/db